### ISSUE TITLE
Makefile errors arch-linux 6.6.7

### ISSUE THREAD

**Issue by Sotem123** [PhilippeBekaert/snd-hdspe#20]
Hello there seems to be a problem with the makefile (or my configuration not sure).

When trying to run make, or dkms following the steps in the readme I receive an error.
When further looking into the output of the dkms install command I see several errors indicating the following:
`warning: "CONFIG_SND_DEBUG" redefined` in several files.
And the other error I am receiving is: `error: implicit declaration of function 'pci_set_consistent_dma_mask'`
Both of the implicit declarations are in the hdspe_core.c file 425:15, 427:23.

**Comment by Schroedingers-Cat** [comment]
The error should be fixed via this PR: https://github.com/PhilippeBekaert/snd-hdspe/pull/12

**Comment by Sotem123** [comment]
Thank for helping out so swiftly!
I figured it was a header file, yet I just found the idea of editing inside of a driver a bit daunting I guess since I have never done so.
I managed to build the drivers using your pull-request.

But seeing the age of the pull request, is the one managing the pull requests no longer active?

And a side-question, if I was to help out with this project what resources could you point me to?
I own 2 RME PCI cards, and I have experience programming embedded C, but never programmed for Linux.

**Comment by jimfrench** [comment]
@Sotem123 

> And a side-question, if I was to help out with this project what resources could you point me to?

Hi, thanks for the offer of help we're currently trying to implement suspend and resume with the MADI and AES cards, which are showing different behaviour apparently. See issue [18](https://github.com/PhilippeBekaert/snd-hdspe/issues/18)

If you are able to do some testing with your cards (which cards are they?) that might really help at the moment. Checkout the suspend-resume branch that @Schroedingers-Cat  has been working on.

ALSA docs are in general a good resource for driver coding.

**Comment by Schroedingers-Cat** [comment]
> But seeing the age of the pull request, is the one managing the pull requests no longer active?  

Prof. Dr. Philippe Bekaert passed away last year (#13).  



> And a side-question, if I was to help out with this project what resources could you point me to?
> I own 2 RME PCI cards, and I have experience programming embedded C, but never programmed for Linux.

The resource I use mostly is this: https://www.kernel.org/doc/html/latest/sound/kernel-api/writing-an-alsa-driver.html#power-management  

You might find some bits in there that seem incomplete our outdated. If you find other resources, I'd be happy to read those!

**Comment by Sotem123** [comment]
@jimfrench @Schroedingers-Cat thanks for your replies!
Very sorry to hear that Prof. Dr. Philippe Bekaert has passed away.

@jimfrench The cards I have are the HDSPe AIO (not PRO) and the HDSPe RAYDAT which I both used as a single card on my Windows setup.

It could take some time for me to dive into this stuff, as I'm not used to linux, coding drivers, kernel related matter, etc.
A long list of things to look into!
I haven't even ever worked on an open-source project this way either.
That said, I do intend to dive into these matters, so in time I'll be able to understand these things better.

So sorry if my question is out of place, but how do you normally communicate for this project?
