### ISSUE TITLE
Changes for kernel 6.12

### ISSUE THREAD

**Issue by siraaris** [PhilippeBekaert/snd-hdspe#24]
I've observed issues with linux v6.12 (rc4).

The driver compiles, but looks like some changes may be needed given changes to ALSA in this version.

Noticing the following kernel logs:

Oct 28 19:07:33 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Card Revision:0: value out of range 210 (0/0) at count 0
Oct 28 19:07:33 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Card Revision:0: access overflow
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Capture PID:0: value out of range -1 (0/0) at count 0
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Capture PID:0: access overflow
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Card Revision:0: value out of range 210 (0/0) at count 0
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Card Revision:0: access overflow
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Firmware Build:0: value out of range 212 (0/0) at count 0
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Firmware Build:0: access overflow
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Playback PID:0: value out of range 1151 (0/0) at count 0
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Playback PID:0: access overflow
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Serial:0: value out of range 24081377 (0/0) at count 0
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Serial:0: access overflow
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 1:0:0:Raw Sample Rate:0: value out of range 220138626867248 (0/0) at count 0
Oct 28 19:22:11 cardia kernel: snd_hdspe 0000:01:00.0: control 1:0:0:Raw Sample Rate:0: access overflow
Oct 28 19:22:47 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Playback PID:0: value out of range 1151 (0/0) at count 0
Oct 28 19:22:47 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Playback PID:0: access overflow
Oct 28 20:43:29 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Firmware Build:0: value out of range 212 (0/0) at count 0
Oct 28 20:43:29 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Firmware Build:0: access overflow
Oct 28 20:43:39 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Firmware Build:0: value out of range 212 (0/0) at count 0
Oct 28 20:43:39 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Firmware Build:0: access overflow
Oct 28 20:43:44 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Firmware Build:0: value out of range 212 (0/0) at count 0
Oct 28 20:43:44 cardia kernel: snd_hdspe 0000:01:00.0: control 0:0:0:Firmware Build:0: access overflow

amixer -c1 controls also errors on some elements (that work in previous kernels):

numid=5,iface=CARD,name='Capture PID'
  ; type=INTEGER,access=r--v----,values=1,min=0,max=0,step=1
amixer: Control sysdefault:1 element read error: Invalid argument

numid=1,iface=CARD,name='Card Revision'
  ; type=INTEGER,access=r-------,values=1,min=0,max=0,step=1
amixer: Control sysdefault:1 element read error: Invalid argument

numid=2,iface=CARD,name='Firmware Build'
  ; type=INTEGER,access=r-------,values=1,min=0,max=0,step=1
amixer: Control sysdefault:1 element read error: Invalid argument

numid=6,iface=CARD,name='Playback PID'
  ; type=INTEGER,access=r--v----,values=1,min=0,max=0,step=1
amixer: Control sysdefault:1 element read error: Invalid argument

numid=3,iface=CARD,name='Serial'
  ; type=INTEGER,access=r-------,values=1,min=0,max=0,step=1
amixer: Control sysdefault:1 element read error: Invalid argument

numid=10,iface=HWDEP,name='Raw Sample Rate'
  ; type=INTEGER64,access=r--v----,values=2,min=0,max=0,step=0
amixer: Control sysdefault:1 element read error: Invalid argument

- and haspeconf doesn't work any more:

root@cardia:/home/aris/proj/hdspeconf# ./hdspeconf 
Card 0 : Loopback 1
Card 1 : RME MADI S/N 24081377 at 0x7f900000 irq 16
ALSA snd_hctl_elem_read error -22: Invalid argument

**Comment by siraaris** [comment]
Changes to ALSA for 6.12 - https://lore.kernel.org/lkml/87wmje9oav.wl-tiwai@suse.de/

**Comment by siraaris** [comment]
I don't think this is 6.12 related. Closing.

**Comment by jimfrench** [comment]
Thanks for closing, although I did test this quickly with 6.12 and AES card and no kernel errors logged on my machine.

**Comment by siraaris** [comment]
Yeah, just a followup - I had defined SND_CTL_INPUT_VALIDATION inadvertently.
